# -*- coding: utf-8 -*-
"""intrusion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bOBGNstbmPB_Ut2bkL7evBdTL5GOT9-c
"""

import os
import numpy as np
import pandas as pd
import cv2
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

ROOT_DIR = '/content/drive/MyDrive/FLYTBASE/flyt'

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics
import ultralytics
ultralytics.checks()

import os

from ultralytics import YOLO
# Load a model
model = YOLO("yolov8n.yaml")  # build a new model from scratch

# Use the model
results = model.train(data=os.path.join(ROOT_DIR, "data.yaml"), epochs=100)  # train the mode





